/*
==========================================================
TFM
School Bus Routing Problem

Este script crea un conjunto de consultas utilizadas para la extracción y preprocesado del trabajo.

Los datos originales procedentes de la Administración
han sido anonimizados para preservar la confidencialidad.
==========================================================
*/

-- Creación estructura datos base para iniciar proyecto sin datos confidenciales.
DROP TABLE SERVICIOS.IA_GRANADA CASCADE CONSTRAINTS;

CREATE TABLE SERVICIOS.IA_GRANADA
(
  BTL_CODIGO     VARCHAR2(10 BYTE),
  TT_ID          NUMBER,
  NEW_TT_ID      NUMBER,
  TT_VALOR       VARCHAR2(150 BYTE),
  TT_ACRONIMO    VARCHAR2(30 BYTE),
  PLAZAS_DESDE   NUMBER,
  PLAZAS_HASTA   NUMBER,
  TT_P1          NUMBER,
  TT_P2          NUMBER,
  TT_P3          NUMBER,
  IMPORTE_DIA    NUMBER,
  TTR_ID         NUMBER                         NOT NULL,
  BTL_DISTANCIA  NUMBER,
  BTL_TIEMPO     NUMBER,
  TRAMO          VARCHAR2(250 BYTE),
  CODIGO_PARADA  VARCHAR2(11 BYTE),
  DESCRIPCION    VARCHAR2(150 BYTE),
  CODIGO         VARCHAR2(8 BYTE)               NOT NULL,
  NIVEL          VARCHAR2(10 BYTE),
  NOMBRE         VARCHAR2(200 BYTE)             NOT NULL,
  PARADA         VARCHAR2(13 BYTE),
  CENTRO         VARCHAR2(10 BYTE),
  ORDEN          NUMBER,
  ALUMNOS        NUMBER,
  MUNICIPIO      VARCHAR2(50 BYTE)
) TABLESPACE PROYECTO_IA;

-- Inserción datos base a partir de colección de vistas materializadas del organismos.
INSERT INTO IA_GRANADA
BTL_CODIGO, TT_ID, NEW_TT_ID, TT_VALOR, TT_ACRONIMO, PLAZAS_DESDE, PLAZAS_HASTA, TT_P1, TT_P2, TT_P3, IMPORTE_DIA, TTR_ID, BTL_DISTANCIA, BTL_TIEMPO, TRAMO, CODIGO_PARADA, DESCRIPCION, CODIGO, NIVEL, NOMBRE, PARADA, CENTRO, ORDEN, ALUMNOS, MUNICIPIO)
SELECT BTL_CODIGO, TT_ID, 0 NEW_TT_ID, TT_VALOR, TT_ACRONIMO, TT_PLAZAS_DESDE PLAZAS_DESDE, NVL(TT_PLAZAS_HASTA,55) PLAZAS_HASTA, TT_P1, TT_P2, TT_P3, 0 IMPORTE_DIA,  
TTR_ID, BTL_DISTANCIA, BTL_TIEMPO, TTR_DESCRIPCION TRAMO, BP_X_PARADA CODIGO_PARADA, BP_DESCRIPCION DESCRIPCION, CODIGO, NIVEL, NOMBRE,
'P-' || BP_X_PARADA PARADA,  'C-' || CODIGO CENTRO, BTPL_ORDEN ORDEN, NVL(BTPL_ALUMNOS_SUBEN,0) + NVL(BTPL_ALUMNOS_PA_SUBEN,0) ALUMNOS, MUNICIPIO
FROM LICITACIONES_TRAYECTOS, EXPEDIENTES, BOLSA_TRAYECTOS_LICITA B, BOLSA_TRAYECTOS_PARADAS_LICITA, DBO.CENTROS_V C, LOTES, 
SERVICIOS.TRANS_BOLSA_PARADAS, TR_TIPOS_TARIFAS TT, SERVICIOS.TRANS_TIPOS_TRAMOS TR, CONTA.UNIDADES_ORG
WHERE LT_EXP_ID = EXP_ID  AND LT_UO_ID = OR_ID AND OR_AUX = '18' -- Provincia de Granada
AND LOT_ID = BTL_LOT_ID AND BTPL_BP_ID = BP_ID
AND MUNICIPIO LIKE '%Motril%'
AND LT_ID = BTL_LT_ID AND BTL_ID = BTPL_BTL_ID AND BTL_SENTIDO = 'I' AND BTPL_CEN_ID_DESTINO = ID AND BTL_TT_ID = TT_ID AND BTL_TTR_ID = TTR_ID
ORDER BY BTL_CODIGO;

-- Extracción Métricas a partir de columnas auxiliares.
SELECT PARADAS, CENTROS, ( PARADAS + CENTROS)  * (PARADAS+ CENTROS) TAMAÑO_MATRIZ
FROM (
SELECT COUNT(DISTINCT CODIGO_PARADA) PARADAS, COUNT(DISTINCT CODIGO) CENTROS FROM IA_GRANADA)

SELECT T.*, PARADAS + CENTROS total, ( PARADAS + CENTROS)  * (PARADAS+ CENTROS) TAMAÑO_MATRIZ
FROM (
SELECT MUNICIPIO, COUNT(DISTINCT CODIGO_PARADA) PARADAS, COUNT(DISTINCT CODIGO) CENTROS FROM IA_GRANADA
GROUP BY MUNICIPIO) T
ORDER BY PARADAS DESC;

SELECT PARADA, CENTRO, SUM(ALUMNOS) ALUMNOS FROM IA_GRANADA
WHERE MUNICIPIO LIKE 'Motril%'
GROUP BY PARADA, CENTRO
ORDER BY 3 DESC;

SELECT SUM(ALUMNOS) FROM IA_GRANADA
WHERE NVL(ALUMNOS, 0) > 0
AND MUNICIPIO LIKE 'Motril%'

SELECT * FROM IA_GRANADA
WHERE NVL(ALUMNOS, 0) = 0;

-- Borrado valores erróneos.
DELETE FROM IA_GRANADA
WHERE NVL(ALUMNOS, 0) = 0;

-- Construcción estructura auxiliar
DROP VIEW SERVICIOS.TFM_ALUMNOS_V;

CREATE OR REPLACE FORCE VIEW SERVICIOS.TFM_ALUMNOS_V
(ORIGEN, CENTRO, ALUMNOS)
BEQUEATH DEFINER
AS 
SELECT 'P-' || BP_X_PARADA ORIGEN, 'C-' || CODIGO CENTRO, SUM(ALUMNOS) ALUMNOS FROM IA_GRANADA
GROUP BY 'P-' || BP_X_PARADA , 'C-' || CODIGO;


SELECT ORIGEN, CENTRO, SUM(ALUMNOS) ALUMNOS FROM TFM_ALUMNOS_V
GROUP BY ORIGEN, CENTRO
ORDER BY ALUMNOS DESC;

SELECT COUNT(*) "Combinaciones Paradas-Centros", SUM(ALUMNOS) "Total Alumnos Transportados", 
AVG(ALUMNOS) "Media Alumnos Parada/Centro", STDDEV(ALUMNOS) "Desviación", MAX(ALUMNOS) "Máximo Alumnos", MIN(ALUMNOS) "Mínimo Alumnos"
FROM (
SELECT ORIGEN, CENTRO, SUM(ALUMNOS) ALUMNOS FROM TFM_ALUMNOS_V
GROUP BY ORIGEN, CENTRO)
ORDER BY ALUMNOS DESC;

SELECT FRANJA, SUM(NUMERO), SUM(ALUMNOS) ALUMNOS
FROM (
SELECT CASE WHEN ALUMNOS = 1 THEN 'ALUMNOS = 1'
                       WHEN ALUMNOS BETWEEN 2 AND 10 THEN 'ENTRE 2 Y 10'
                       WHEN ALUMNOS BETWEEN 11 AND 25 THEN 'ENTRE 11 Y 25'
                       WHEN ALUMNOS BETWEEN 26 AND 50 THEN 'ENTRE 26 Y 50'
                       WHEN ALUMNOS BETWEEN 51 AND 75 THEN 'ENTRE 51 Y 75'
                       WHEN ALUMNOS BETWEEN 75 AND 100 THEN 'ENTRE 51 Y 75' END FRANJA, 1 NUMERO, ALUMNOS 
FROM (
SELECT ORIGEN, CENTRO, SUM(ALUMNOS) ALUMNOS FROM TFM_ALUMNOS_V
GROUP BY ORIGEN, CENTRO)
) GROUP BY FRANJA
ORDER BY 2;

SELECT ORIGEN, CENTRO, SUM(ALUMNOS) ALUMNOS FROM TFM_ALUMNOS_V
GROUP BY ORIGEN, CENTRO;

SELECT DISTINCT BTL_CODIGO, CODIGO_PARADA
FROM IA_GRANADA
WHERE MUNICIPIO LIKE '%Motril%'
AND ALUMNOS > 0;

-- Enlace para pintar la ruta de un trayecto.
CREATE OR REPLACE PROCEDURE PINTA_TRAYECTO (P_ID_N IN NUMBER) IS
    V_COORS_T   VARGS_V;
BEGIN
    SELECT COORDENADAS
    BULK COLLECT INTO V_COORS_T
    FROM ITINERARIOS_PRODUCCION_V
    WHERE RUTA = P_ID_N
    ORDER BY ORDEN;    
    DBMS_OUTPUT.PUT_LINE(PK_COORDENADAS.ENLACE_INDICACIONES(V_COORS_T));
END;    

    
FUNCTION ENLACE_INDICACIONES(P_COORDENADAS_T VARGS_V) RETURN CLOB IS
V_ENLACE_C  CLOB;
BEGIN
SELECT 'https://www.google.com/maps/dir/' || LISTAGG(COLUMN_VALUE, '/') WITHIN GROUP(ORDER BY ROWNUM)
INTO V_ENLACE_C
FROM TABLE(P_COORDENADAS_T);

RETURN V_ENLACE_C;
END ENLACE_INDICACIONES;